### ISSUE TITLE
How to kill process?

### ISSUE THREAD

**Issue by mikhail-m1** [knsd/daemonize#13]
Does crate provide any way to kill (restart) currently working daemon?

**Comment by knsd** [comment]
Hello, Mikhail.

No, it doesn't, but you can read [pid file](http://knsd.github.io/daemonize/daemonize/struct.Daemonize.html#method.pid_file) and send a signal to daemon instead.

**Comment by mikhail-m1** [comment]
If you are ready to accept pull request I'll do it
