### ISSUE TITLE
systemd can not read the pid file correctly....

### ISSUE THREAD

**Issue by Matrix-Zhang** [knsd/daemonize#15]
systemd will print :

Failed to read PID from file xxx.pid: Invalid argument

my service file content is
`[Unit]
Description="Cloud Scale System Socket Server"
After=network.target postgresql.service

[Service]
Type=forking
PIDFile=xxx.pid
Environment="RUST_LOG=cloud_scale_system=debug,cs_server=debug" "RUST_BACKTRACE=1"
StandardOutput=journal
ExecStart=/usr/bin/xxxx
Restart=always

[Install]
WantedBy=multi-user.target`

right now my solution is comment the 'PIDFile=xxx.pid' line, and add 'GuessMainPID=true'

**Comment by knsd** [comment]
Hi!

Looks like systemd requires an absolute file name for `PIDFile` option.

**Comment by Matrix-Zhang** [comment]
here xxx.pid is absolute path for the PIDFile

**Comment by mikhail-m1** [comment]
I've found this bug too, I've solved it by adding delay after fork in parent process. Systemd reads pid file immediately after exits of parent process, and it's empty.

**Comment by mikhail-m1** [comment]
https://github.com/mikhail-m1/daemonize/commit/3c27a97291c1fa086df415cf4399fee0c874d999

**Comment by knsd** [comment]
There is `Daemonize::execute` method in `maser`, it's possible to [delay](https://github.com/knsd/daemonize/blob/a6cbcf4a2f1b5edec5f56c58a2a62640cf5596d0/daemonize-tests/src/lib.rs#L241) parent process exiting with it until pid is written.
