### ISSUE TITLE
privileged_action example

### ISSUE THREAD

**Issue by greenpdx** [knsd/daemonize#26]
I want to open a input device and I need to do it before dropping into nobody.  I am not sure how to setup that function. Could I get an exmple?

**Comment by eun-ice** [comment]
```rust
   let daemonize = Daemonize::new().user("nobody");
   let daemonize = daemonize.privileged_action(move || { return open_device(); });
    match daemonize.start() {
        Ok(device) => {
               println!("Device opened {:?}", device),
        }
        Err(e) => eprintln!("Error, {}", e),
    }
```

Maybe you ran into https://github.com/knsd/daemonize/pull/27 
With the current version you will get an [E0507](https://doc.rust-lang.org/error-index.html#E0507) as soon as you want to move anything inside the closure.

**Comment by greenpdx** [comment]
I will try it
