### ISSUE TITLE
Recent changes break armv7

### ISSUE THREAD

**Issue by vkrasnov** [knsd/daemonize#34]
In line https://github.com/knsd/daemonize/blob/master/src/lib.rs#L447
Libc on 64bit architectures want *i8 but on arvm7 they want *u8. The best way to support multiple platforms is to use `as _` so it casts to the correct pointer depending on the plartform.

**Comment by vkrasnov** [comment]
Thanks!

**Comment by knsd** [comment]
Fixed in [0.4.1](https://crates.io/crates/daemonize/0.4.1), thanks!
