### ISSUE TITLE
Not possible to not redirect stdio?

### ISSUE THREAD

**Issue by andrewshadura** [knsd/daemonize#40]
Hi,

I’d like to daemonise but keep stderr and stdout unredirected, but it seems it’s not possible to do currently?

**Comment by wfraser** [comment]
Where would you have its output go, if it's not redirected? Daemons by definition don't have a terminal associated with them.

**Comment by andrewshadura** [comment]
Well, I want to be able to keep stderr/stdout from the parent process until
I manually close them, so that I can print diagnostics after daemonising.

Some error conditions are difficult to detect before daemonisation.

**Comment by mikma** [comment]
@wfraser 
> Where would you have its output go, if it's not redirected? Daemons by definition don't have a terminal associated with them.

If you run a daemon as a forking sub-process in systemd then the output would by default go into the journal, but that's configurable in the systemd unit.

The `daemon` function in glibc also has a `noclose` argument which indicates the use case isn't too uncommon.

I found a commit by @vorner in #28 which allows disabling of redirection when staying in the foreground. But that could be changed with a small edit.

**Comment by knsd** [comment]
I'm going to add `Stdio::keep()` constructor in 0.5.0.
