### ISSUE TITLE
question - is this cross platform?

### ISSUE THREAD

**Issue by avnerbarr** [knsd/daemonize#43]
will it run on windows/linux/mac? 
thanks

**Comment by Alexhuszagh** [comment]
It can't be: it extensively uses `std::os::unix` in its imports, which seems to be preventing this from working.

**Comment by eun-ice** [comment]
I can confirm daemonize to work flawlessly on mac and linux.

**Comment by Alexhuszagh** [comment]
> I can confirm daemonize to work flawlessly on mac and linux.

Definitely, it just extensively uses Unix functionality, which isn't supported on Windows. So it will support all Unix-like systems very robustly, just not sure how you'd implement this on Windows.

**Comment by knsd** [comment]
This library aims to support any Unix system, Windows support is out of scope for now.
