### ISSUE TITLE
Is this crate maintained?

### ISSUE THREAD

**Issue by woodruffw** [knsd/daemonize#44]
Hi there!

I'm looking for a daemonization crate for Rust, and this one looks both well-featured and popular. However, it hasn't had any contribution activity in a while. Is anybody still maintaining this crate? If not, I'm happy to spend some time working on the outstanding PRs, as well as making any idiomatic improvements that present themselves.

**Comment by TornaxO7** [comment]
I'd be happy as well to know if this crate is still maintained or not.

**Comment by woodruffw** [comment]
Revisiting this: if there's interest from the community, I'm happy to maintain a semi-permanent fork of this repository that addresses the concerns in the top comment (open issues, modernization, etc.).

Please put a 👍  or 👎  here to register interest 🙂

**Comment by TornaxO7** [comment]
@knsd or could you please respond us?

**Comment by TornaxO7** [comment]
@woodruffw I could also think that I can help you a bit with this (like as a co-maintainer) if it's ok for you.

**Comment by woodruffw** [comment]
> @woodruffw I could also think that I can help you a bit with this (like as a co-maintainer) if it's ok for you.

Yep, that works for me. I'll create a repo and share access with you once we get a little more buy-in from current users.

**Comment by TornaxO7** [comment]
Should I share this issue to other platforms like discord or reddit?

**Comment by woodruffw** [comment]
Up to you! I'd personally give it a couple of days -- it's already a relatively popular crate and I'm sure other people will chime in.

**Comment by knsd** [comment]
This library is occasionally maintained, I'm planning to release a new version in two weeks.

**Comment by woodruffw** [comment]
Thanks for the update! Glad to hear it.

**Comment by douglascaetano** [comment]
Hi @knsd, any plans for the new release?
