### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by thesharp** [knsd/daemonize#6]
root@freebsd-1gb-lon1-01:~/daemonize # cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading tempdir v0.3.4
 Downloading quick-error v0.1.4
 Downloading winapi-build v0.1.1
 Downloading debug-builders v0.1.0
 Downloading log v0.3.4
 Downloading syslog v3.1.0
 Downloading rand v0.3.13
 Downloading time v0.1.34
 Downloading libc v0.1.12
 Downloading advapi32-sys v0.1.2
 Downloading kernel32-sys v0.2.1
 Downloading unix_socket v0.4.6
 Downloading libc v0.2.4
 Downloading winapi v0.2.5
   Compiling debug-builders v0.1.0
   Compiling winapi v0.2.5
   Compiling libc v0.1.12
   Compiling libc v0.2.4
   Compiling quick-error v0.1.4
   Compiling winapi-build v0.1.1
   Compiling unix_socket v0.4.6
   Compiling log v0.3.4
   Compiling daemonize v0.1.1 (file:///root/daemonize)
src/ffi.rs:52:6: 52:20 error: unresolved name `errno_location` [E0425]
src/ffi.rs:52     *errno_location()
                   ^~~~~~~~~~~~~~
src/ffi.rs:52:6: 52:20 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
   Compiling advapi32-sys v0.1.2
   Compiling kernel32-sys v0.2.1
Build failed, waiting for other jobs to finish...
Could not compile `daemonize`.

To learn more, run the command again with --verbose.
root@freebsd-1gb-lon1-01:~/daemonize # cargo --version
cargo 0.4.0 (built 2016-01-05)
root@freebsd-1gb-lon1-01:~/daemonize # rustc --version
rustc 1.5.0

**Comment by knsd** [comment]
Can you please test current git head?

**Comment by thesharp** [comment]
root@freebsd-1gb-lon1-01:~/daemonize # cargo test
   Compiling daemonize v0.1.1 (file:///root/daemonize)
   Compiling kernel32-sys v0.2.1
   Compiling advapi32-sys v0.1.2
   Compiling time v0.1.34
   Compiling rand v0.3.13
   Compiling syslog v3.1.0
   Compiling tempdir v0.3.4
     Running target/debug/daemonize-48bd7eef5ebf8345

running 2 tests
test ffi::test_get_gid_by_name ... ok
test ffi::test_get_uid_by_name ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/tests-a5b240df6ff3f942

running 3 tests
test double_run ... ok
test test_chdir ... ok
test test_pid ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests daemonize

running 1 test
test _0 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
